In [1]:
import numpy

In [2]:
def NN(m1, m2, w1, w2, b):
    z = m1 * w1 + m2 * w2 + b
    return sigmoid(z)

def sigmoid(x):
    return 1/(1 + numpy.exp(-x))

In [3]:
w1 = numpy.random.randn()
w2 = numpy.random.randn()
b = numpy.random.randn()
NN(3, 1.5, w1, w2, b)

In [5]:
phrases = ['看起來像', '我猜是', '可能是', '看起來是', '猜測....']
data = [[3, 1.5, 1], [2, 1, 0], [4, 1.5, 1], [3.5, 5, 1], [2, 0.5, 0], [5.5, 1, 1]]

In [29]:
rand_data = data[numpy.random.randint(len(data))]
m1 = rand_data[0]
m2 = rand_data[1]
prediction = NN(m1, m2, w1, w2, b)
prediction_text = ['藍色','紅色'][int(numpy.round(prediction))]
result = numpy.random.choice(phrases) + "" + prediction_text
result

'猜測....紅色'

In [30]:
a = '真的是' + ['藍色','紅色'][rand_data[2]]
a

'真的是紅色'

In [31]:
import numpy as np

In [34]:
X = np.array( [[1,0,1,0], [1,0,1,1], [0,1,0,1]] )
y = np.array ( [[1], [1], [0]] )

In [35]:
def sigmoid(x):
    return 1/(1 + numpy.exp(-x)) 
def derivatives_sigmoid(x):
    return x * (1 - x)

In [36]:
#Variable initialization
epoch = 5000
lr = 0.1 
inputlayer_neurons = X.shape[1]
hiddenlayer_neurons = 10
output_neurons = 1

In [37]:
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

In [58]:
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1 = np.dot(hiddenlayer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
    #Backpropagation
    E = y-output
    numpy_E = np.array(E)
    Loss_E = np.sum((numpy_E)**2)/len(numpy_E) 
    back_output_layer = derivatives_sigmoid(output)
    back_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = Loss_E * back_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hiddenlayer) * lr
    bh += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr
    if i % 1000 == 0:
        print("Epoch:{} loss {}".format(i, Loss_E))
        
print('actual:\n', y, '\n')
print('predicted:\n', output)

Epoch:0 loss 4.943095933890527e-05
Epoch:1000 loss 4.854409376155291e-05
Epoch:2000 loss 4.768734669871144e-05
Epoch:3000 loss 4.6859228185461235e-05
Epoch:4000 loss 4.605834431367514e-05
actual:
 [[1]
 [1]
 [0]] 

predicted:
 [[0.99672362]
 [0.99290179]
 [0.00864484]]


In [59]:
## neural network in pytorch
import torch
import numpy as np

#Input array
X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y = torch.Tensor([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
  return 1/(1 + torch.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

#Variable initialization
epoch=1000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 10 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh=torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor) #1=size
wout=torch.randn(hiddenlayer_neurons, output_neurons)
bout=torch.randn(1, output_neurons)#1=size

#wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons)) #均勻分布
#bh=np.random.uniform(size=(1,hiddenlayer_neurons))
#wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
#bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):

  #Forward Propogation
  hidden_layer_input1 = torch.mm(X, wh) # torch.mm = np.dot
  hidden_layer_input = hidden_layer_input1 + bh
  hidden_layer_activations = sigmoid(hidden_layer_input)
 
  output_layer_input1 = torch.mm(hidden_layer_activations, wout)
  output_layer_input = output_layer_input1 + bout
  output = sigmoid(output_layer_input1)

  #Backpropagation
  E = y-output
  back_output_layer = derivatives_sigmoid(output)
  back_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
  d_output = E * back_output_layer
  Error_at_hidden_layer = torch.mm(d_output, wout.t())
  d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
  wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
  bout += d_output.sum() *lr
  wh += torch.mm(X.t(), d_hiddenlayer) *lr
  bh += d_output.sum() *lr
 
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 tensor([[1.],
        [1.],
        [0.]]) 

predicted :
 tensor([[0.9519],
        [0.9441],
        [0.0725]])
